name: control_gastos
description: Aplicaci칩n para el control de gastos personales.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  vector_math: ^2.1.4
  # Nuevas dependencias
  pdf: ^3.10.7
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  open_file: ^3.3.2
  fl_chart: ^0.66.0
  share_plus: ^7.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Configuraci칩n del icono de la aplicaci칩n
flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#2E7D32"  # Verde que coincide con tema
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"

flutter:
  uses-material-design: true

  # A침adir la carpeta de assets para los iconos
  assets:
    - assets/icon/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Light.ttf
          weight: 300